[package]
name = "inversion_api_codegen"
version = "0.0.1"
authors = ["neonphog <neonphog@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
